version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1
  node: circleci/node@1.1.6

commands:
  add-dist-folder-to-git:
    steps:
      - run: ls
      - run: pwd
      - run: cp -r build dist
      - run: git config user.email "commits-noreply@github.com"
      - run: git config user.name "github-pipelines"
      - run: git add .
      - run: git commit -m "add dist folder"

jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: /app
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn dev:test
            - run: yarn dev:build
            - run: ls
            - run: pwd
            - persist_to_workspace:
                # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
                # taken to be the root directory of the workspace.
                root: build
                # Must be relative path from root
                paths:
                  - ./
  deploy:
    executor:
      name: heroku/default
    steps:
      - checkout
      - heroku/install
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./build
      - add-dist-folder-to-git
      - heroku/deploy-via-git

workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only:
                - master
                - development
